#ifndef PT2_CUTS_H
#define PT2_CUTS_H

#include <cmath>   // NAN, std::isnan
#include <limits>

#include "pt2.h"

// Generated by tools/plot_cuts.py --cpp -- do not edit by hand.
// Input:  output/pt2_cutstudy.root
// Sample: all   NaN policy: pass   MIN_FAKE_PER_REAL: 1.0
// Measured on that sample: signal efficiency 54.442%, fake kept 0.0215%, real/fake 6.171
//
// Indexed [comboIdx][chargeIdx], chargeIdx 0 = positive, 1 = negative.
// Bounds are INCLUSIVE. A NAN bound means that side is not cut.
//
// Apply them all at once with pt2_cuts::passAll(pt2, lsPt); `pass` below is
// the single-variable building block if you want to test one in isolation.

namespace pt2_cuts {

// Ambiguity resolution (-a N) ranks competing pT2s by
//     chi2 = sum over the four helical residuals of (res/sigma)^2
// with these sigmas: the 68% spread of |residual| over real pT2s.
constexpr double kSigmaXY0 = 0.325176;
constexpr double kSigmaZ0  = 0.047054;
constexpr double kSigmaXY1 = 0.552739;
constexpr double kSigmaZ1  = 0.077080;

// true when the value is inside the window for this zone; a NAN bound
// is simply not applied, and an uncomputable value passes (matching
// the NaN policy this was tuned with: pass).
inline bool pass(int combo, int charge, double v,
                 const double lo[13][2], const double hi[13][2]) {
    if (combo < 0 || combo > 12 || charge < 0 || charge > 1) return false;
    if (std::isnan(v)) return true;
    const double l = lo[combo][charge];
    const double h = hi[combo][charge];
    if (!std::isnan(l) && v < l) return false;
    if (!std::isnan(h) && v > h) return false;
    return true;
}

    constexpr double dBeta_lo[13][2] = {
        {    -0.026474,    -0.116400 },  // L1F_to_L2F
        {    -0.031440,    -0.027246 },  // L1F_to_L2T
        {    -0.026474,    -0.116400 },  // L1T_to_L2F
        {    -0.031440,    -0.027246 },  // L1T_to_L2T
        {    -0.022258,    -0.018034 },  // L1T_to_E1PS
        {    -0.017688,    -0.025895 },  // L2F_to_L3F
        {    -0.022788,    -0.024367 },  // L2F_to_L3T
        {    -0.017688,    -0.025895 },  // L2T_to_L3F
        {    -0.022788,    -0.024367 },  // L2T_to_L3T
        {    -0.026437,    -0.021127 },  // L2T_to_E1PS
        {    -0.019526,    -0.019257 },  // E1PS_to_E2PS
        {    -0.105358,    -0.089620 },  // E1PS_to_E22S
        {    -0.024939,    -0.032774 },  // E2PS_to_E3PS
    };

    constexpr double dBeta_hi[13][2] = {
        {     0.028481,     0.053931 },  // L1F_to_L2F
        {     0.036639,     0.022991 },  // L1F_to_L2T
        {     0.028481,     0.053931 },  // L1T_to_L2F
        {     0.036639,     0.022991 },  // L1T_to_L2T
        {     0.023048,     0.018994 },  // L1T_to_E1PS
        {     0.019392,     0.022648 },  // L2F_to_L3F
        {     0.023713,     0.023156 },  // L2F_to_L3T
        {     0.019392,     0.022648 },  // L2T_to_L3F
        {     0.023713,     0.023156 },  // L2T_to_L3T
        {     0.023883,     0.022843 },  // L2T_to_E1PS
        {     0.020044,     0.017692 },  // E1PS_to_E2PS
        {     0.086287,     0.094832 },  // E1PS_to_E22S
        {     0.027190,     0.026967 },  // E2PS_to_E3PS
    };

    constexpr double heli_dXY0_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double heli_dXY0_hi[13][2] = {
        {     0.236108,     0.315653 },  // L1F_to_L2F
        {     0.393784,     0.338941 },  // L1F_to_L2T
        {     0.236108,     0.315653 },  // L1T_to_L2F
        {     0.393784,     0.338941 },  // L1T_to_L2T
        {     0.404949,     0.370782 },  // L1T_to_E1PS
        {     0.420737,     0.545991 },  // L2F_to_L3F
        {     0.624053,     0.673763 },  // L2F_to_L3T
        {     0.420737,     0.545991 },  // L2T_to_L3F
        {     0.624053,     0.673763 },  // L2T_to_L3T
        {     0.765020,     0.745962 },  // L2T_to_E1PS
        {     0.793609,     0.765405 },  // E1PS_to_E2PS
        {     2.059512,     2.089453 },  // E1PS_to_E22S
        {     0.881747,     0.953490 },  // E2PS_to_E3PS
    };

    constexpr double heli_dXY1_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double heli_dXY1_hi[13][2] = {
        {     0.665083,     0.822676 },  // L1F_to_L2F
        {     0.969384,     0.853923 },  // L1F_to_L2T
        {     0.665083,     0.822676 },  // L1T_to_L2F
        {     0.969384,     0.853923 },  // L1T_to_L2T
        {     0.634404,     0.576023 },  // L1T_to_E1PS
        {     0.842947,     1.099082 },  // L2F_to_L3F
        {     1.266718,     1.346439 },  // L2F_to_L3T
        {     0.842947,     1.099082 },  // L2T_to_L3F
        {     1.266718,     1.346439 },  // L2T_to_L3T
        {     1.149283,     1.112561 },  // L2T_to_E1PS
        {     0.901135,     0.860861 },  // E1PS_to_E2PS
        {     2.851792,     2.796917 },  // E1PS_to_E22S
        {     1.015076,     1.086534 },  // E2PS_to_E3PS
    };

    constexpr double heli_dZ0_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double heli_dZ0_hi[13][2] = {
        {     0.138705,     0.174634 },  // L1F_to_L2F
        {     0.108638,     0.098324 },  // L1F_to_L2T
        {     0.138705,     0.174634 },  // L1T_to_L2F
        {     0.108638,     0.098324 },  // L1T_to_L2T
        {     0.050691,          NAN },  // L1T_to_E1PS
        {     0.235284,     0.267576 },  // L2F_to_L3F
        {     0.198111,     0.207951 },  // L2F_to_L3T
        {     0.235284,     0.267576 },  // L2T_to_L3F
        {     0.198111,     0.207951 },  // L2T_to_L3T
        {     0.132355,     0.143068 },  // L2T_to_E1PS
        {     0.093941,          NAN },  // E1PS_to_E2PS
        {     0.404031,     0.341418 },  // E1PS_to_E22S
        {     0.086354,     0.093487 },  // E2PS_to_E3PS
    };

    constexpr double heli_dZ1_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double heli_dZ1_hi[13][2] = {
        {     0.298198,     0.377469 },  // L1F_to_L2F
        {     0.222993,     0.202267 },  // L1F_to_L2T
        {     0.298198,     0.377469 },  // L1T_to_L2F
        {     0.222993,     0.202267 },  // L1T_to_L2T
        {     0.079518,          NAN },  // L1T_to_E1PS
        {     0.375524,     0.441413 },  // L2F_to_L3F
        {     0.338714,     0.344180 },  // L2F_to_L3T
        {     0.375524,     0.441413 },  // L2T_to_L3F
        {     0.338714,     0.344180 },  // L2T_to_L3T
        {     0.175719,     0.183530 },  // L2T_to_E1PS
        {     0.098752,          NAN },  // E1PS_to_E2PS
        {     0.895578,     0.839325 },  // E1PS_to_E22S
        {          NAN,     0.101513 },  // E2PS_to_E3PS
    };

    constexpr double ls_pt_lo[13][2] = {
        {          NAN,     0.575923 },  // L1F_to_L2F
        {     0.568754,     0.568860 },  // L1F_to_L2T
        {          NAN,     0.575923 },  // L1T_to_L2F
        {     0.568754,     0.568860 },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {     0.588966,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {     0.588966,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double ls_pt_hi[13][2] = {
        {          NAN,     0.833291 },  // L1F_to_L2F
        {     0.835262,     0.832211 },  // L1F_to_L2T
        {          NAN,     0.833291 },  // L1T_to_L2F
        {     0.835262,     0.832211 },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {     0.803239,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {     0.803239,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double rz_simple0_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {    -0.385184,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {    -0.385184,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double rz_simple0_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {     0.091850,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {     0.091850,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double rz_simple1_lo[13][2] = {
        {          NAN,   -12.334288 },  // L1F_to_L2F
        {    -1.145319,    -1.120954 },  // L1F_to_L2T
        {          NAN,   -12.334288 },  // L1T_to_L2F
        {    -1.145319,    -1.120954 },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {    -6.671327,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double rz_simple1_hi[13][2] = {
        {          NAN,    12.095509 },  // L1F_to_L2F
        {    -0.042633,    -0.006490 },  // L1F_to_L2T
        {          NAN,    12.095509 },  // L1T_to_L2F
        {    -0.042633,    -0.006490 },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {    -0.592557,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double delta_pt_lo[13][2] = {
        {    -0.057790,    -0.062773 },  // L1F_to_L2F
        {    -0.072311,    -0.068621 },  // L1F_to_L2T
        {    -0.057790,    -0.062773 },  // L1T_to_L2F
        {    -0.072311,    -0.068621 },  // L1T_to_L2T
        {    -0.106382,    -0.097391 },  // L1T_to_E1PS
        {    -0.030870,    -0.038948 },  // L2F_to_L3F
        {    -0.040209,    -0.046635 },  // L2F_to_L3T
        {    -0.030870,    -0.038948 },  // L2T_to_L3F
        {    -0.040209,    -0.046635 },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {    -0.097243,    -0.083094 },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,    -0.081583 },  // E2PS_to_E3PS
    };

    constexpr double delta_pt_hi[13][2] = {
        {     0.064152,     0.078499 },  // L1F_to_L2F
        {     0.082282,     0.071866 },  // L1F_to_L2T
        {     0.064152,     0.078499 },  // L1T_to_L2F
        {     0.082282,     0.071866 },  // L1T_to_L2T
        {     0.088695,     0.080693 },  // L1T_to_E1PS
        {     0.038285,     0.048010 },  // L2F_to_L3F
        {     0.050960,     0.053896 },  // L2F_to_L3T
        {     0.038285,     0.048010 },  // L2T_to_L3F
        {     0.050960,     0.053896 },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {     0.079255,     0.073764 },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,     0.062169 },  // E2PS_to_E3PS
    };

    constexpr double delta_eta_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {    -0.097215,    -0.089807 },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double delta_eta_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {     0.097538,     0.095753 },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double zResKin_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double zResKin_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double delta_phi_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double delta_phi_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double lst_dPhi_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double lst_dPhi_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double betaIn_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double betaIn_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {          NAN,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double zResGeo_lo[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {   -24.673212,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };

    constexpr double zResGeo_hi[13][2] = {
        {          NAN,          NAN },  // L1F_to_L2F
        {          NAN,          NAN },  // L1F_to_L2T
        {          NAN,          NAN },  // L1T_to_L2F
        {          NAN,          NAN },  // L1T_to_L2T
        {          NAN,          NAN },  // L1T_to_E1PS
        {          NAN,          NAN },  // L2F_to_L3F
        {          NAN,          NAN },  // L2F_to_L3T
        {          NAN,          NAN },  // L2T_to_L3F
        {          NAN,          NAN },  // L2T_to_L3T
        {          NAN,          NAN },  // L2T_to_E1PS
        {          NAN,          NAN },  // E1PS_to_E2PS
        {    27.172251,          NAN },  // E1PS_to_E22S
        {          NAN,          NAN },  // E2PS_to_E3PS
    };


// ---------------------------------------------------------------------------
// Everything below is hand-written and survives regeneration by plot_cuts.py.
// ---------------------------------------------------------------------------

// The thresholds were tuned against NaN-for-invalid, so the sentinel values
// computeFeatures() leaves behind (-999, -1, ...) have to be folded back to
// NaN first: -999 compared as a number would be rejected outright instead of
// skipped, which is not what the tuning saw.
inline double valid(double v, double sentinel) {
    return (v > sentinel) ? v : std::numeric_limits<double>::quiet_NaN();
}

// true when a pT2 survives every tuned cut for its zone and charge.
// `lsPt` is reader.ls_pt->at(pt2.ls_idx); it is not carried on the struct.
inline bool passAll(const pT2 &p, double lsPt) {
    if (p.combo_idx < 0 || p.charge_idx < 0) return false;
    if (p.heli.size() < 4) return false;

    const int c = p.combo_idx, q = p.charge_idx;
    const bool heliOK = (p.heli[0] >= 0);
    const double kNaN = std::numeric_limits<double>::quiet_NaN();

    const double dXY0 = heliOK ? p.heli[0] : kNaN;
    const double dZ0  = heliOK ? p.heli[1] : kNaN;
    const double dXY1 = heliOK ? p.heli[2] : kNaN;
    const double dZ1  = heliOK ? p.heli[3] : kNaN;
    const bool rzOK   = (p.rz_simple.first > -900);
    const double rz0  = rzOK ? p.rz_simple.first  : kNaN;
    const double rz1  = rzOK ? p.rz_simple.second : kNaN;

    // Same order as the CUTS chain the thresholds were tuned with. Order does
    // not change the outcome of a box cut; keeping them aligned just makes the
    // two sides easy to compare.
    if (!pass(c, q, valid(p.delta_beta, -100.0), dBeta_lo,     dBeta_hi))     return false;
    if (!pass(c, q, dXY0,                        heli_dXY0_lo, heli_dXY0_hi)) return false;
    if (!pass(c, q, dXY1,                        heli_dXY1_lo, heli_dXY1_hi)) return false;
    if (!pass(c, q, dZ0,                         heli_dZ0_lo,  heli_dZ0_hi))  return false;
    if (!pass(c, q, dZ1,                         heli_dZ1_lo,  heli_dZ1_hi))  return false;
    if (!pass(c, q, lsPt,                        ls_pt_lo,     ls_pt_hi))     return false;
    if (!pass(c, q, rz0,                         rz_simple0_lo, rz_simple0_hi)) return false;
    if (!pass(c, q, rz1,                         rz_simple1_lo, rz_simple1_hi)) return false;
    if (!pass(c, q, p.delta_pt,                  delta_pt_lo,  delta_pt_hi))  return false;
    if (!pass(c, q, p.delta_eta,                 delta_eta_lo, delta_eta_hi)) return false;
    if (!pass(c, q, valid(p.z_res_kin, -100.0),  zResKin_lo,   zResKin_hi))   return false;
    if (!pass(c, q, p.delta_phi,                 delta_phi_lo, delta_phi_hi)) return false;
    if (!pass(c, q, valid(p.lst_delta_phi, -100.0), lst_dPhi_lo, lst_dPhi_hi)) return false;
    if (!pass(c, q, valid(p.beta_in, -100.0),    betaIn_lo,    betaIn_hi))    return false;
    if (!pass(c, q, valid(p.z_res_geo, -100.0),  zResGeo_lo,   zResGeo_hi))   return false;
    return true;
}

// Ranking score for ambiguity resolution: how far the pLS extrapolation misses
// the two mini-doublets, in units of the spread seen on real pT2s. Smaller is
// better. A pT2 with no helical extrapolation cannot be compared, so it is
// pushed to the back of the queue rather than silently winning.
inline double ambiguityChi2(const pT2 &p) {
    if (p.heli.size() < 4 || !(p.heli[0] >= 0))
        return std::numeric_limits<double>::max();
    const double a = p.heli[0] / kSigmaXY0, b = p.heli[1] / kSigmaZ0;
    const double c = p.heli[2] / kSigmaXY1, d = p.heli[3] / kSigmaZ1;
    return a * a + b * b + c * c + d * d;
}

}  // namespace pt2_cuts

#endif  // PT2_CUTS_H
